[package]
name = "core-plugin-calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
regex = "1.9.6"
num-traits = "0.2.9"
libc = "0.2.9"
plugin-api = { path = "../../plugin-api/" }
serde = {version = "1.0.9", features = ["derive"]}
